name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sudo npm install -g n
          sudo n latest

      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.11 python3-pip
          sudo ln -s /usr/bin/python3.11 /usr/bin/python

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          python -m pytest

      - name: Build Docker image
        run: docker build -t puc_producao .

      - name: Start Docker container
        run: docker run -d -p 5000:5000 puc_producao